### ISSUE TITLE
DeletionTimestamp being added to parent resource doesn't trigger a resync

### ISSUE THREAD

**Issue by herojan** [calebamiles/metacontroller#125]
Hi, I've been looking at using composite controller with an empty list of children to control an external service via my own CRD. Everything works fine with regard to creating resources and updating them and I don't currently need to put changes from the external system back into the resource. 

The issue I have is that metacontroller doesn't seem to notice when a deletionTimestamp is placed in the metadata of a parent resource. So when I try to delete the custom resource, the deletionTimestamp is created by k8s but metacontroller doesn't react with a request to my controller. If I modify the resource in some other way though (changing something in its spec), then metacontroller sees the change, notices the deletionTimestamp and deletes the resource after the finalize request to my controller. It's just a hack project so I can work around it for now via a resync period but it's not ideal.

Is this intended behaviour or even a desired use-case?

**Comment by groner** [comment]
I'm seeing something like this also.  #122 might fix it.

**Comment by enisoc** [comment]
Thanks for reporting. I agree that #122 should fix it. I'm reviewing that PR now.
